#--------------------------------
#       All paths
#--------------------------------

#------------------------
#   General Parameters
#-------------------------

cell_x :
cell_y : 
cell_z :

grid_size : 3

#------------------------
#   Geometry Parameters
#-------------------------

geometry:
  #Fused silica
  loc_x_fused_silica: 
  loc_y_fused_silica: 
  loc_z_fused_silica: 

  size_x_fused_silica: 
  size_y_fused_silica: 
  size_z_fused_silica: 0.78

  material_index_fused_silica: 1.44

  #PDMS
  loc_x_pdms:
  loc_y_pdms:
  loc_z_pdms:
  
  size_x_pdms:
  size_y_pdms:
  size_z_pdms: 1.56

  material_index_pdms: 1.4

  #Buffer
  substrate_buffer: True
  size_x_buffer: 5.0
  size_y_buffer: 5.0
  size_z_buffer: 4

  #Metasurface
  neighborhood_size: [3,3] #nx,ny

  atom_type: 'cylinder'
  material_index_meta_atom : 3.48 #amorphous silica
  unit_cell_size: 0.68
  height_pillar: 1.02
  radius_pillar:
  radius_min: 0.075
  radius_max: 0.250


  #Boundaries
  thickness_pml: 0.78

#-----------------------
#   Source Parameters
#-----------------------

source:
  type: 'gaussian'
  frequency:
  wavelength: 1.55
  loc_x_source:
  loc_y_source:
  loc_z_source:
  size_x_source: 
  size_y_source:
  size_z_source: 0 
  fwidth: 1.2
  fcen:
  component:

#-----------------------
#   Monitor Parameters
#-----------------------

monitor:
  components_dft_monitor: 'all'
  fcen:
  freq_list:
  wavelenth_center: 1.55
  wavelength_list: [2.881, 1.650, 1.550, 1.300, 1.060]

dft_slice_monitor:
  components_dft_monitor: 'all'
  fcen:
  freq_list:
  wavelenth_center: 1.55
  wavelength_list: [2.881, 1.650, 1.550, 1.300, 1.060]
  loc_z: [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4.0]

#------------------------
#   Simulation Parameters
#-------------------------
simulation:
  resolution : 10
  decay_rate : 0.0015
  dt : 50
  source_component:
  center_mon_z: 

#-----------------------
#  Animation Params
#----------------------

plot_plane :
fps : 20
