path_image: docker.io/kovaleskilab/meep:v2_with_torch
path_template: kube_files/templates/job.txt

path_simulations: /develop/results
path_logs: /develop/results/current_logs
path_sim_job_files: /develop/results/job_files
path_out_sims: /develop/results # this is really a duplicate. can change 'path_simulations' in run_datagen.py (template) if you want to clean this up.

num_mem_lim: 800G
num_mem_req: 600G
num_cpus_per_op: 48
num_cpus: 48
#num_cpus_total: 2048
num_parallel_ops: 10 
#num_cpus_total: 160

namespace: gpn-mizzou-muem
kill_time_min: 30
#kill_tag: preprocess
kill_tag: slicing

# Define Simulation

num_sims: 9 # this is the ending index
start_group_id: 0 
