apiVersion: v1
kind: Pod
metadata:
  name: monitor-dataset-volume
spec:
  containers:
    - name: monitor-dataset-volume
      image: docker.io/kovaleskilab/meep:v3_lightning      
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: dft-volumes
          mountPath: /develop/results
  volumes:
    - name: dft-volumes
      persistentVolumeClaim:
        claimName: dft-volumes

  restartPolicy: Never

