apiVersion: v1
kind: Pod
metadata:
  name: monitor-volumes
spec:
  containers:
    - name: dft-volumes-volumes
      image: docker.io/kovaleskilab/ml_basic:v4-kube    
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: dft-volumes-refidx
          mountPath: /develop/results
  volumes:
    - name: dft-volumes-refidx
      persistentVolumeClaim:
        claimName: dft-volumes-refidx

  restartPolicy: Never

