apiVersion: v1
kind: Pod
metadata:
  name: monitor-dataset
spec:
  containers:
    - name: monitor-dataset
      image: docker.io/kovaleskilab/meep:v3_lightning      
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: nfe-data
          mountPath: /develop/results
  volumes:
    - name: nfe-data
      persistentVolumeClaim:
        claimName: nfe-data

  restartPolicy: Never

