
apiVersion: batch/v1
kind: Job
metadata:
  name: buffer-sim-000000
spec:
  template:
    spec:
      containers:
        - name: buffer-sim-000000
          image: docker.io/kovaleskilab/meep:v2_with_torch
          command: ["/bin/sh", "-c"]
          args: ["git clone https://github.com/Kovaleski-Research-Lab/general_3x3.git;
                cd general_3x3;
                pwd > /develop/results/current_logs/'zero'.log;
                git status > /develop/results/current_logs/'one'.log;
                git checkout andy_branch;
                git status > /develop/results/current_logs/'two'.log;
                python3 test.py > /develop/results/current_logs/'three'.log;
                mpirun --allow-run-as-root --np 48 python3 run.py -idx 0 > /develop/results/current_logs/0.log"]
          resources:
            limits:
              memory: 240G
              cpu: 48
            requests:
              memory: 200G
              cpu: 48
          volumeMounts:
            - name: buffer-study
              mountPath: /develop/results

      volumes:
        - name: buffer-study
          persistentVolumeClaim:
            claimName: buffer-study

      restartPolicy: Never